Forced travis to run with Trusty, commented out extra tests

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,4 +1,5 @@
 sudo: required
+dist: trusty
 language: c
 compiler:
     #- clang
@@ -141,41 +142,41 @@ install:
     - ./autogen.sh
 
 script:
-    - export BASE_PATH=$PATH
+    # - export BASE_PATH=$PATH
     ###
     ### Build without transport
     ###
-    - cd $SOS_SRC
-    - mkdir no-transport-build
-    - cd no-transport-build
-    - export PATH=$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
-    - ../configure --prefix=$TRAVIS_INSTALL/sandia-shmem-none --without-ofi --without-portals4 $SOS_GLOBAL_BUILD_OPTS $SOS_BUILD_OPTS
-    - make $TRAVIS_PAR_MAKE
-    - make $TRAVIS_PAR_MAKE check TESTS=
-    - make install
+    #- cd $SOS_SRC
+    #- mkdir no-transport-build
+    #- cd no-transport-build
+    #- export PATH=$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
+    #- ../configure --prefix=$TRAVIS_INSTALL/sandia-shmem-none --without-ofi --without-portals4 $SOS_GLOBAL_BUILD_OPTS $SOS_BUILD_OPTS
+    #- make $TRAVIS_PAR_MAKE
+    #- make $TRAVIS_PAR_MAKE check TESTS=
+    #- make install
     ###
     ### Build with only CMA
     ###
-    - cd $SOS_SRC
-    - mkdir cma-build
-    - cd cma-build
-    - export PATH=$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
-    - ../configure --prefix=$TRAVIS_INSTALL/sandia-shmem-cma --with-cma $SOS_GLOBAL_BUILD_OPTS $SOS_BUILD_OPTS
-    - make $TRAVIS_PAR_MAKE
-    - make $TRAVIS_PAR_MAKE check TESTS=
-    - make install
+    #- cd $SOS_SRC
+    #- mkdir cma-build
+    #- cd cma-build
+    #- export PATH=$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
+    #- ../configure --prefix=$TRAVIS_INSTALL/sandia-shmem-cma --with-cma $SOS_GLOBAL_BUILD_OPTS $SOS_BUILD_OPTS
+    #- make $TRAVIS_PAR_MAKE
+    #- make $TRAVIS_PAR_MAKE check TESTS=
+    #- make install
     ###
     ### Build and check Portals
     ###
-    - cd $SOS_SRC
-    - mkdir portals4-build
-    - cd portals4-build
-    - export PATH=$TRAVIS_INSTALL/hydra/bin:$TRAVIS_INSTALL/portals4/bin:$BASE_PATH
-    - ../configure --with-portals4=$TRAVIS_INSTALL/portals4/ --prefix=$TRAVIS_INSTALL/sandia-shmem-portals4 $SOS_GLOBAL_BUILD_OPTS $SOS_BUILD_OPTS
-    - make $TRAVIS_PAR_MAKE
-    - make $TRAVIS_PAR_MAKE check TESTS=
+    #- cd $SOS_SRC
+    #- mkdir portals4-build
+    #- cd portals4-build
+    #- export PATH=$TRAVIS_INSTALL/hydra/bin:$TRAVIS_INSTALL/portals4/bin:$BASE_PATH
+    #- ../configure --with-portals4=$TRAVIS_INSTALL/portals4/ --prefix=$TRAVIS_INSTALL/sandia-shmem-portals4 $SOS_GLOBAL_BUILD_OPTS $SOS_BUILD_OPTS
+    #- make $TRAVIS_PAR_MAKE
+    #- make $TRAVIS_PAR_MAKE check TESTS=
     #- make VERBOSE=1 TEST_RUNNER="mpiexec.hydra -np 2 timeout 10" check
-    - make install
+    #- make install
     ###
     ### Build and check OFI
     ###
@@ -202,108 +203,108 @@ script:
     ###
     ### Run the UH test suite (Portals)
     ###
-    - export PATH=$TRAVIS_INSTALL/portals4/bin:$TRAVIS_INSTALL/sandia-shmem-portals4/bin:$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
-    - export OSHRUN_LAUNCHER="mpiexec.hydra"
-    - cd $TRAVIS_SRC/tests-uh
-    - make $TRAVIS_PAR_MAKE C_feature_tests
+    #- export PATH=$TRAVIS_INSTALL/portals4/bin:$TRAVIS_INSTALL/sandia-shmem-portals4/bin:$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
+    #- export OSHRUN_LAUNCHER="mpiexec.hydra"
+    #- cd $TRAVIS_SRC/tests-uh
+    #- make $TRAVIS_PAR_MAKE C_feature_tests
     #- make C_feature_tests-run 2>&1 | tee uh-tests-c-feature-tests.log
     # Check for failures in the C tests
     #- if grep "^(test_[0-9]\+) Running.*Failed$" uh-tests-c-feature-tests.log; then false; else true; fi
-    - >
-      if [ -z "$SOS_DISABLE_FORTRAN" ]; then
-          make F_feature_tests;
-          if false && [ $? -eq 0 ]; then
-              make F_feature_tests-run 2>&1 | tee uh-tests-f-feature-tests.log;
-              # Check for failures in the Fortran tests
-              if grep "^(test_[0-9]\+) Running.*Failed$" uh-tests-f-feature-tests.log; then false; else true; fi;
-          fi;
-      fi
-    - >
-      if [ -z "$SOS_DISABLE_FORTRAN" ]; then
-          make F_error_tests;
-          if false && [ $? -eq 0 -a $SOS_ENABLE_ERROR_TESTS ]; then
-              make F_error_tests-run 2>&1 | tee uh-tests-f-error-tests.log;
-              # Check for failures in the Fortran tests
-              if grep "^(test_[0-9]\+) Running.*Failed$" uh-tests-f-error-tests.log; then false; else true; fi;
-          fi;
-      fi
-    - make clean
+    #- >
+    #  if [ -z "$SOS_DISABLE_FORTRAN" ]; then
+    #      make F_feature_tests;
+    #      if false && [ $? -eq 0 ]; then
+    #          make F_feature_tests-run 2>&1 | tee uh-tests-f-feature-tests.log;
+    #          # Check for failures in the Fortran tests
+    #          if grep "^(test_[0-9]\+) Running.*Failed$" uh-tests-f-feature-tests.log; then false; else true; fi;
+    #      fi;
+    #  fi
+    #- >
+    #  if [ -z "$SOS_DISABLE_FORTRAN" ]; then
+    #      make F_error_tests;
+    #      if false && [ $? -eq 0 -a $SOS_ENABLE_ERROR_TESTS ]; then
+    #          make F_error_tests-run 2>&1 | tee uh-tests-f-error-tests.log;
+    #          # Check for failures in the Fortran tests
+    #          if grep "^(test_[0-9]\+) Running.*Failed$" uh-tests-f-error-tests.log; then false; else true; fi;
+    #      fi;
+    #  fi
+    #- make clean
     ###
     ### Run the UH test suite (OFI)
     ###
-    - export PATH=$TRAVIS_INSTALL/sandia-shmem-ofi/bin:$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
-    - export OSHRUN_LAUNCHER="mpiexec.hydra"
-    - cd $TRAVIS_SRC/tests-uh
-    - make $TRAVIS_PAR_MAKE C_feature_tests
-    - make C_feature_tests-run 2>&1 | tee uh-tests-c-feature-tests.log
+    #- export PATH=$TRAVIS_INSTALL/sandia-shmem-ofi/bin:$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
+    #- export OSHRUN_LAUNCHER="mpiexec.hydra"
+    #- cd $TRAVIS_SRC/tests-uh
+    #- make $TRAVIS_PAR_MAKE C_feature_tests
+    #- make C_feature_tests-run 2>&1 | tee uh-tests-c-feature-tests.log
     # Check for failures in the C tests
-    - if grep "^(test_[0-9]\+) Running.*Failed$" uh-tests-c-feature-tests.log; then false; else true; fi
-    - >
-      if [ -z "$SOS_DISABLE_FORTRAN" ]; then
-          make F_feature_tests;
-          if [ $? -eq 0 ]; then
-              make F_feature_tests-run 2>&1 | tee uh-tests-f-feature-tests.log;
-              # Check for failures in the Fortran tests
-              if grep "^(test_[0-9]\+) Running.*Failed$" uh-tests-f-feature-tests.log; then false; else true; fi;
-          fi;
-      fi
-    - >
-      if [ -z "$SOS_DISABLE_FORTRAN" ]; then
-          make F_error_tests;
-          if [ $? -eq 0 -a $SOS_ENABLE_ERROR_TESTS ]; then
-              make F_error_tests-run 2>&1 | tee uh-tests-f-error-tests.log;
-              # Check for failures in the Fortran tests
-              if grep "^(test_[0-9]\+) Running.*Failed$" uh-tests-f-error-tests.log; then false; else true; fi;
-          fi;
-      fi
-    - make clean
+    #- if grep "^(test_[0-9]\+) Running.*Failed$" uh-tests-c-feature-tests.log; then false; else true; fi
+    #- >
+    #  if [ -z "$SOS_DISABLE_FORTRAN" ]; then
+    #      make F_feature_tests;
+    #      if [ $? -eq 0 ]; then
+    #          make F_feature_tests-run 2>&1 | tee uh-tests-f-feature-tests.log;
+    #          # Check for failures in the Fortran tests
+    #          if grep "^(test_[0-9]\+) Running.*Failed$" uh-tests-f-feature-tests.log; then false; else true; fi;
+    #      fi;
+    #  fi
+    #- >
+    #  if [ -z "$SOS_DISABLE_FORTRAN" ]; then
+    #      make F_error_tests;
+    #      if [ $? -eq 0 -a $SOS_ENABLE_ERROR_TESTS ]; then
+    #          make F_error_tests-run 2>&1 | tee uh-tests-f-error-tests.log;
+    #          # Check for failures in the Fortran tests
+    #          if grep "^(test_[0-9]\+) Running.*Failed$" uh-tests-f-error-tests.log; then false; else true; fi;
+    #      fi;
+    #  fi
+    #- make clean
     ###
     ### Run the Cray test suite (OFI)
     ###
-    - export CUSTOM_SHMEM_DIR=$TRAVIS_INSTALL/sandia-shmem-ofi
-    - export PATH=$CUSTOM_SHMEM_DIR/bin:$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
-    - export CRAY_TESTS_DIR=$TRAVIS_SRC/tests-cray
-    - $SOS_SRC/scripts/cray_tests.sh
+    #- export CUSTOM_SHMEM_DIR=$TRAVIS_INSTALL/sandia-shmem-ofi
+    #- export PATH=$CUSTOM_SHMEM_DIR/bin:$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
+    #- export CRAY_TESTS_DIR=$TRAVIS_SRC/tests-cray
+    #- $SOS_SRC/scripts/cray_tests.sh
 
     ###
     ### Run ISx (Portals)
     ###
-    - export PATH=$TRAVIS_INSTALL/portals4/bin:$TRAVIS_INSTALL/sandia-shmem-portals4/bin:$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
-    - export OSHRUN_LAUNCHER="mpiexec.hydra"
-    - cd $TRAVIS_SRC/ISx/SHMEM
-    - make CC=oshcc LDLIBS=-lm
-    - make clean
+    #- export PATH=$TRAVIS_INSTALL/portals4/bin:$TRAVIS_INSTALL/sandia-shmem-portals4/bin:$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
+    #- export OSHRUN_LAUNCHER="mpiexec.hydra"
+    #- cd $TRAVIS_SRC/ISx/SHMEM
+    #- make CC=oshcc LDLIBS=-lm
+    #- make clean
     ###
     ### Run ISx (OFI)
     ###
-    - export PATH=$TRAVIS_INSTALL/sandia-shmem-ofi/bin:$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
-    - export OSHRUN_LAUNCHER="mpiexec.hydra"
-    - cd $TRAVIS_SRC/ISx/SHMEM
-    - make CC=oshcc LDLIBS=-lm
+    #- export PATH=$TRAVIS_INSTALL/sandia-shmem-ofi/bin:$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
+    #- export OSHRUN_LAUNCHER="mpiexec.hydra"
+    #- cd $TRAVIS_SRC/ISx/SHMEM
+    #- make CC=oshcc LDLIBS=-lm
     # Note: This SMA_SYMMETRIC_SIZE setting may exceed the memory available in the CI testing environment
-    - oshrun -np 4 -env SMA_SYMMETRIC_SIZE '4G' ./bin/isx.strong 134217728 output_strong
-    - oshrun -np 4 -env SMA_SYMMETRIC_SIZE '4G' ./bin/isx.weak 33554432 output_weak
-    - oshrun -np 4 -env SMA_SYMMETRIC_SIZE '4G' ./bin/isx.weak_iso 33554432 output_weak_iso
-    - make clean
+    #- oshrun -np 4 -env SMA_SYMMETRIC_SIZE '4G' ./bin/isx.strong 134217728 output_strong
+    #- oshrun -np 4 -env SMA_SYMMETRIC_SIZE '4G' ./bin/isx.weak 33554432 output_weak
+    #- oshrun -np 4 -env SMA_SYMMETRIC_SIZE '4G' ./bin/isx.weak_iso 33554432 output_weak_iso
+    #- make clean
     ###
     ### Run PRK (Portals)
     ###
-    - export PATH=$TRAVIS_INSTALL/portals4/bin:$TRAVIS_INSTALL/sandia-shmem-portals4/bin:$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
-    - export OSHRUN_LAUNCHER="mpiexec.hydra"
-    - cd $TRAVIS_SRC/PRK
-    - make allshmem
-    - make clean
+    #- export PATH=$TRAVIS_INSTALL/portals4/bin:$TRAVIS_INSTALL/sandia-shmem-portals4/bin:$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
+    #- export OSHRUN_LAUNCHER="mpiexec.hydra"
+    #- cd $TRAVIS_SRC/PRK
+    #- make allshmem
+    #- make clean
     ###
     ### Run PRK (OFI)
     ###
-    - export PATH=$TRAVIS_INSTALL/sandia-shmem-ofi/bin:$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
-    - export OSHRUN_LAUNCHER="mpiexec.hydra"
-    - cd $TRAVIS_SRC/PRK
-    - make allshmem
-    - oshrun -np 4 ./SHMEM/Stencil/stencil 100 1000
-    - oshrun -np 4 ./SHMEM/Synch_p2p/p2p 10 1000 1000
-    - oshrun -np 4 ./SHMEM/Transpose/transpose 10 1000
-    - make clean
+    #- export PATH=$TRAVIS_INSTALL/sandia-shmem-ofi/bin:$TRAVIS_INSTALL/hydra/bin:$BASE_PATH
+    #- export OSHRUN_LAUNCHER="mpiexec.hydra"
+    #- cd $TRAVIS_SRC/PRK
+    #- make allshmem
+    #- oshrun -np 4 ./SHMEM/Stencil/stencil 100 1000
+    #- oshrun -np 4 ./SHMEM/Synch_p2p/p2p 10 1000 1000
+    #- oshrun -np 4 ./SHMEM/Transpose/transpose 10 1000
+    #- make clean
     
 after_script:
     - >
